# Ders Notu Week-5: NumPy

- Bu hafta Python'da bilimsel hesaplamalar için kullanılan NumPy kütüphanesini öğreniyoruz. 
- Notebook boyunca temel veri yapıları, işlemler ve örnek uygulamalara yer vereceğiz.


## 1. NumPy Nedir ve Neden Kullanılır?

NumPy (Numerical Python), Python programlama dili için güçlü bir **bilimsel hesaplama kütüphanesidir**.

**Neden NumPy?**
- 🚀 **Verimlilik:** NumPy dizileri, yerleşik Python listelerinden çok daha hızlıdır.
- 🧱 **Temel Kütüphane:** Pandas, SciPy, scikit-learn gibi birçok kütüphane NumPy üzerine kuruludur.
- 💾 **Bellek Yönetimi:** Daha az bellek kullanır ve büyük veri setleriyle çalışırken performansı artırır.
- ✨ **Kolay Kullanım:** Matematiksel işlemleri sadeleştirir ve kodu okunabilir hale getirir.
- 🌐 **Topluluk:** Geniş bir kullanıcı topluluğu ve bolca öğretici kaynak bulunur.

- Numpy, dizilerle çalışmak için kullanılır. Bunun yanında doğrusal cebir, matris gibi alanlarda kullanılır.
- Yapı ve işlev olarak listelerle benzer olsada listelerden çok daha hızlıdırlar.
  
📺 *Video önerisi:*  
[What is NumPy? (YouTube)](https://youtu.be/QUT1VHiLmmI?si=8I_ElT978Sj_I25i)

In [47]:
!pip install numpy

In [48]:
import numpy as np

## Array (Dizi)

- Array (dizi), aynı türdeki elemanları sıralı bir şekilde saklayan bir veri yapısıdır. np.array() fonksiyonu, verilen bir Python listesi, tuple'ı veya başka bir dizi benzeri nesneyi alır ve bu nesneyi bir NumPy array'ine dönüştürür.

In [49]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [50]:
type(a)

numpy.ndarray

- "N-dimensional array" (N boyutlu dizi) anlamına gelir

- NumPy array'leri homojen veri tipine sahiptir, yani tüm elemanlar aynı veri tipinde olmalıdır.

In [51]:
arr = np.array([3, 15.4, 6,7.8])
arr

array([ 3. , 15.4,  6. ,  7.8])

## Data Type

- .dtype : array elemanlarının hangi türde veri içerdiğini anlamamıza yardımcı olur.

In [52]:
arr.dtype

dtype('float64')

In [53]:
arr2 = np.array([3.5, 20, 10, 15.6], dtype = "int")
arr2

array([ 3, 20, 10, 15])

In [54]:
arr2.dtype

dtype('int64')

In [55]:
arr2 = np.array([3.5, 20, 10, 15.6], dtype = "str")
arr2 #U yani Unicode karakter kullanan, en fazla 4 karakter içeren bir string arrayi old. ifade ediyor.
#dtype='<U4'

array(['3.5', '20', '10', '15.6'], dtype='<U4')

## DİZİLERDEKİ BOYUTLAR

**0-D Arrays (Sıfır Boyutlu Diziler)**

- Sıfır boyutlu array, sadece tek bir değeri tutan en temel NumPy array'idir.

- Bu tür array'ler, daha büyük ve çok boyutlu array'lerin yapı taşları olarak düşünülebilir.

In [56]:
np.array(36)

array(36)

**1-D Arrays (Bir Boyutlu Diziler)**


- 1-D Arrays (Bir Boyutlu Diziler), NumPy'da tek bir eksende düzenlenmiş elemanlardan oluşan dizilerdir.

❗️Notlar
- Elemanlar arasında bir satır veya sütun ayrımı yoktur — sadece düz bir sıra vardır.
Bu yapı, matematikteki vektör kavramıyla eşdeğerdir.

In [57]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

**2-D Arrays (İki Boyutlu Diziler)**

- 2-D Arrays (İki Boyutlu Diziler), NumPy'da satırlar ve sütunlar içeren veri yapılarıdır. Bu diziler, tabular veriyi temsil eder ve genellikle matris veya tablo şeklinde düzenlenmiş verilerle çalışırken kullanılır. İki boyutlu diziler matrislerdir.


  - En az bir satır ve bir sütun içerir.
  - Liste içinde liste yapısı kullanılarak tanımlanır.
  - Matris olarak da adlandırılır.

In [58]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

**3-D Arrays (Üç Boyutlu Diziler)**

- 3-D Arrays (Üç Boyutlu Diziler), NumPy'da üç boyutta düzenlenmiş veri elemanlarını temsil eder. Bu diziler, veri kümesinin derinlik, satır ve sütun olmak üzere üç boyutta düzenlenmesini sağlar ve genellikle üç boyutlu veri yapılarıyla çalışırken kullanılır.

- Belirttiğiniz dizinin 3 boyutlu olması için tüm alt dizilerin aynı sayıda satır ve sütun içermesi gerekir. NumPy, dizinin her boyutunun aynı şekle sahip olmasını bekler, bu yüzden iç içe geçmiş dizilerin şekli tutarlı olmalıdır.

In [59]:
np.array([[[1,2,3],[4,5,6]],
         [[1,2,3],[4,5,6]]])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

- .ndim: .ndim özelliği, NumPy array'inin kaç boyuttan oluştuğunu belirtir. Bu, array'in yapısının derinliğini anlamamıza yardımcı olur.

In [60]:
array0 = np.array(36)
array1 = np.array([1,2,3,4])
array2 = np.array([[1,2,3],[4,5,6]])
array3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(array0.ndim)
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)

0
1
2
3


- ndmin ile kendimiz boyutu belirleyebiliriz.

In [61]:
np.array([1,2,3,4], ndmin = 4)

array([[[[1, 2, 3, 4]]]])

## Indexing

In [62]:
#1-D
array1

array([1, 2, 3, 4])

- 1. indeximize erişmek istersek:

In [63]:
array1[1]

2

In [64]:
#2-D
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
array2[0,2]

3

In [66]:
array2[1,1]

5

- Derinlik (Depth)
- Satır Sayısı (Rows)
- Sütun Sayısı (Columns)
  - [derinlik, satır, sütün]

In [68]:
array3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [72]:
array3[1,0,2]

3

## Slicing

In [75]:
#1-D
array1

array([1, 2, 3, 4])

In [81]:
array1[2:]

array([3, 4])

In [82]:
array1[2:4]

array([3, 4])

In [85]:
array1[0:3]

array([1, 2, 3])

In [89]:
#2-D
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
array2[0:2,2]

array([3, 6])

In [105]:
#3-D
array3 #[başlangıç:son, başlangıç:son, başlangıç:son)

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [107]:
array3[0:1,0:3]

array([[[1, 2, 3],
        [4, 5, 6]]])

In [110]:
array3[1,0:2,1]

array([2, 5])

In [113]:
array3[0,0,1:3]

array([2, 3])

## Temel Numpy Fonksiyonları
**Size**

- Arrayde bulunan eleman sayısını verir.

In [115]:
print(array1)
print(array1.size)

[1 2 3 4]
4


**Shape**

- özelliği, NumPy dizisinin her bir boyutundaki eleman sayısını içeren bir tuple döndürür.

In [117]:
array1

array([1, 2, 3, 4])

In [118]:
np.shape(array1)

(4,)

In [122]:
print(array2)
np.shape(array2)

[[1 2 3]
 [4 5 6]]


(2, 3)

In [123]:
print(array3)
np.shape(array3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


(2, 2, 3)

**Reshape**

- NumPy'deki reshape işlemi, bir dizinin şeklini değiştirmek için kullanılır.

- Bu işlem, dizinin elemanlarının sayısını değiştirmeden dizinin boyutlarını yeniden düzenler.

- Örneğin, 12 elemanlı bir dizi yalnızca 3x4, 4x3, 6x2 gibi toplamda 12 eleman olan şekillere dönüştürülebilir.

In [124]:
arr_new = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr_new)
print(np.shape(arr_new))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [126]:
#yeniden boyutlandırma yapma: 6 satır ve 2 sütundan oluşturma
arr_new.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [127]:
arr_new.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [130]:
arr_new.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [131]:
arr_new.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [132]:
arr_new.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [135]:
# -1 bir boyutun otomatik olarak tanımlanmasını sağlar.
arr_new.reshape(3,2,-1)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])